---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=old-test-loader

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: jYS1ZMOn+54LctBnRGLM4JccV5UrWw5X2N+u+8PcYXLwlfO1ajhCuXMCO41qzix3qDi6GSv/hisVyZAaYz6D9wj0iRfp7lpOQlfBcm5Nnkko+L43ftXEdecseZMYptMZaUf48ynV7xsvJ4AILSzLJCM3aazr6WOkknVGCEN0Y1c=
  on:
    tags: true
    repo: ember-cli/ember-cli-qunit
